# Generated by Selenium IDE
# import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

driver = webdriver.Chrome()

# 1 | open | / |
driver.get("https://www.amazon.eg/")

# 2 | setWindowSize | 974x1032 |
driver.set_window_size(974, 1032)

# 3 | mouseOver | id=nav-link-accountList-nav-line-1 |
element = driver.find_element(By.ID, "nav-link-accountList-nav-line-1")
actions = ActionChains(driver)
actions.move_to_element(element).perform()

# 4 | click | xpath=//a[@id='nav-link-accountList']/div/span |
driver.find_element(By.XPATH, "//a[@id=\'nav-link-accountList\']/div/span").click()

# 5 | type | xpath=//input[@id='ap_email'] | esmaeil.abdalraziq@gmail.com
driver.find_element(By.XPATH, "//input[@id='ap_email']").send_keys("esmaeil.abdalraziq@gmail.com")
driver.find_element(By.XPATH, "//input[@id='continue']").click()

# 6 | type | xpath=//input[@id='ap-credential-autofill-hint'] | **********
driver.find_element(By.XPATH, "//input[@id='ap_password']").send_keys("**********")
driver.find_element(By.XPATH, "//input[@id='continue']").click()


# 10 | click | xpath=//input[@id='signInSubmit'] |
driver.find_element(By.XPATH, "//input[@id=\'signInSubmit\']").click()

# # 11 | click | xpath=//input[@id='input-box-otp'] |
# driver.find_element(By.XPATH, "//input[@id=\'input-box-otp\']").click()
#
# # 12 | type | xpath=//input[@id='input-box-otp'] | 171100
# driver.find_element(By.XPATH, "//input[@id=\'input-box-otp\']").send_keys("171100")
#
# # 13 | sendKeys | xpath=//input[@id='input-box-otp'] | ${KEY_ENTER}
# driver.find_element(By.XPATH, "//input[@id=\'input-box-otp\']").send_keys(Keys.ENTER)

# 14 | mouseOver | css=.a-carousel-goto-prevpage |
element = driver.find_element(By.CSS_SELECTOR, ".a-carousel-goto-prevpage")

driver.quit()

# actions = ActionChains(self.driver)
# actions.move_to_element(element).perform()

